plugins {
    id 'java-library'
    id 'maven-publish'
}
java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
    withSourcesJar()
}
dependencies { api project(':protocol') }
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all', '-Werror']
}
tasks.register('apiTest', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'org.customvision.api.ApiTests'
    workingDir rootProject.projectDir
}
check.dependsOn apiTest
